version: "3"
services:
  hub:
    image: selenium/hub:4.1.0
#    ports:                          - it is not required for remote tests execution
#      - "4444:4444"
  chrome:
    image: selenium/node-chrome:4.1.0
    shm_size: '2g'
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  firefox:
    image: selenium/node-firefox:4.1.0
    #    increase the size of share to fix an issue with insufficient memory size for firefox browser
    shm_size: '2g'
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    #    below we define two test modules to execute out tests in parallel containers
  test-firefox-module:
    image: aksionauivan/selenium-docker
    depends_on:
      - firefox
    environment:
      - HUB_HOST=hub
      - MODULE=search-module.xml
      - BROWSER=firefox
    volumes:
      - ./search-result-firefox:/test/test-output
  test-chrome-module:
    image: aksionauivan/selenium-docker
    depends_on:
      - chrome
    environment:
      - HUB_HOST=hub
      - MODULE=search-module.xml
      - BROWSER=chrome
    volumes:
      - ./search-result-chrome:/test/test-output